import { ChangeEvent, MouseEventHandler, ReactElement, ReactNode } from "react"

export type Params = {
    [key: string]: any
}


export interface ColumnsProps {
    field: string,
    headerName: string,
    width: string | number,
    renderCell?: (params: Params, action: (e?: ChangeEvent<HTMLInputElement>, user?: User) => void) => ReactNode | ReactElement
    actionsItem?: (params: Params, action: (e?: ChangeEvent<HTMLInputElement>, user?: User) => void) => ReactNode | ReactElement
}
export interface User {
    birthday?: string;
    email?: string;
    name?: string;
    id?: string;
    auth0_id?: string;
    lastname?: string;
    middlename?: string;
    second_lastname?:string
    phone?: string;
    timezone?: string;
    language?: string;
    /* image?:string;
    is_admin?:boolean; */
}


export interface TableFooterProps<Data> {
    callBack: (number: number) => void,
    range: number[],
    setPage: any,
    page: number,
    slice: Data[],
    totalItems: number,
    setRowsPerPage:any,
}

// Generated by https://quicktype.io

export interface UserTable {
    data: User;
}



export interface Image {
    file_name: string;
    updated_at: string;
}